changes

diff --git a/.github/workflows/release_dekomart.yml b/.github/workflows/release_dekomart.yml
--- a/.github/workflows/release_dekomart.yml
+++ b/.github/workflows/release_dekomart.yml
@@ -23,18 +23,19 @@ jobs:
         with:
           node-version: '22.x'
 
-      - name: Install Chrome dependencies and Puppeteer
+      - name: Install Chrome dependencies and Puppeteer (safe mode)
         run: |
           sudo apt-get update
           sudo apt-get install -y wget gnupg unzip \
             fonts-liberation libappindicator3-1 \
-            libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 \
+            libatk-bridge2.0-0t64 libatk1.0-0t64 libcups2t64 libdbus-1-3 \
             libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 \
             libxcomposite1 libxdamage1 libxrandr2 xdg-utils \
             libasound2t64
           cd CartifyWebApi
           npm install
-          npx --yes puppeteer browsers install chrome
+          npx --yes puppeteer browsers install chrome || echo "Puppeteer install fallback failed"
+
 
       - name: Build project
         run: |
